### ISSUE TITLE
Magsafe indication

### ISSUE THREAD

**Issue by Rahuletto** [mhaeuser/Battery-Toolkit#13]
### Suggestion
> This suggestion helps alot of mac users with MagSafe charger connectors

Would be cool if it can change the magsafe indication when it stops charging at maximum level,
im not sure if its possible or can be done.

**Comment by mhaeuser** [comment]
I'm not sure this is software-controlled. How does it work with Apple's Optimized Charging? I never checked.

**Comment by Rahuletto** [comment]
There was this app called BatFi which does it for free tho, which controls magsafe and still with Optimized charging
