### ISSUE TITLE
"Battery Toolkit" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by MECK187** [mhaeuser/Battery-Toolkit#18]
Hi - I'm running macOS 14.5 and can't install the latest App version (1.4). I get the following error message: 

**"Battery Toolkit" can't be opened because Apple cannot check it for malicious software.** 

Screenshot attached.

![Screenshot 2024-05-22 at 14 44 47](https://github.com/mhaeuser/Battery-Toolkit/assets/170530713/c88322cf-067a-43c8-a10d-f9727b48be1a)

**Comment by mhaeuser** [comment]
That’s to be expected, because I use development certificates for signing. You can bypass this with Right Click > Open.
