### ISSUE TITLE
"Sync MagSafe indicator light" not available in settings

### ISSUE THREAD

**Issue by Azirine** [mhaeuser/Battery-Toolkit#20]
Unlike what is shown in the readme, "Sync MagSafe indicator light" is not available in the settings.
![power](https://github.com/mhaeuser/Battery-Toolkit/assets/101342773/e388c23c-60d3-4fa9-83f2-0e767645cc58)
Battery Toolkit version 1.4
MacOS 14.5

**Comment by mhaeuser** [comment]
This is unlucky versioning, the README does not currently reflect the state of the release, but of the pre-release repo contents. I planned to do a release earlier, but then I wanted to add Homebrew support for the next one, with however is currently blocked. Maybe I will release soon without Homebrew support.
