### ISSUE TITLE
Background Activity Issues

### ISSUE THREAD

**Issue by shubh30112003** [mhaeuser/Battery-Toolkit#21]
<img width="372" alt="Screenshot 2024-06-15 at 11 07 19 AM" src="https://github.com/mhaeuser/Battery-Toolkit/assets/121214849/c7173bb1-3a11-466a-a866-642268aef15e">
<img width="328" alt="Screenshot 2024-06-15 at 11 09 52 AM" src="https://github.com/mhaeuser/Battery-Toolkit/assets/121214849/dfa3a48f-c959-4027-b5aa-dcb779786406">

I tried uninstalling and installing again but it didnt work.

Macos 15, Macbook Pro M1 Pro, 2021

**Comment by mhaeuser** [comment]
macOS 15 is a buggy beta, I’m not sure what you expect. I heard from another user who hit the same issue and a simple reboot fixed the issue. In case the system is now tainted, try these steps: https://github.com/mhaeuser/Battery-Toolkit/issues/7#issuecomment-2036664963

**Comment by shubh30112003** [comment]
@mhaeuser Thanks for prompt reply.  I did delete with every file but didnt work, I tried again. no success

**Comment by mhaeuser** [comment]
The steps entail more than simply deleting files, and more importantly, they entail two different routes based on an unobvious condition I have no control over. Please read them thoroughly.

**Comment by shubh30112003** [comment]
i meant i did run command. Man i loved the app. until 15 becomes stable i cannot use the app

**Comment by crystall1nedev** [comment]
Sequoia beta 2 seems to fix the issue for me. This exact situation is why it's a good idea not to run beta software if you aren't ready to deal with software breakage.
