### ISSUE TITLE
Battery discharges with power adapter enabled

### ISSUE THREAD

**Issue by Azirine** [mhaeuser/Battery-Toolkit#22]
Under a ~30W load with a 96W charger, the battery discharges to the lower limit set in the app then charges up again. Power adapter is set to be enabled. Expected behaviour is all power will be taken from the power adapter without draining the battery.
![battery](https://github.com/mhaeuser/Battery-Toolkit/assets/101342773/4edab980-37d7-43b7-b273-d6c3dbf9f7e3)
Battery Toolkit 1.4, MacOS 14.5

**Comment by mhaeuser** [comment]
Well, are you sure it’s a consistent 30 W load? Macs, especially the 16”, will use the battery if AC is not enough. Battery Toolkit has no control whatsoever over this behaviour.

**Comment by Azirine** [comment]
I have a 14" MBP which should not be able to use more power than the 96W charger can provide. ~30W is seen under Mx Power Gadget, which along with monitor, etc. (monitor is set to medium-low brightness) should only be around ~40W.

**Comment by mhaeuser** [comment]
I can’t find any hard facts on this right now, but I think it can very well use more than 96W, especially the Max models. The 16” just has a better thermal headroom to sustain the high clock speeds (and supports faster charging), I’m not aware of it having a larger maximum theoretical power draw. And again, the tool cannot influence this behaviour either way.

**Comment by Azirine** [comment]
To show I was not using more power than the adapter, I let the battery charge under the same load, and despite being under load the battery was still charging with 13 W.
![bat](https://github.com/mhaeuser/Battery-Toolkit/assets/101342773/c3c64cab-d970-402e-93c6-82547295c357)
