### ISSUE TITLE
Build from sources using release scheme leads to "Type 'BTPowerEvents' has no member 'getPercentRemaining'" error

### ISSUE THREAD

**Issue by mrdc** [mhaeuser/Battery-Toolkit#25]
Hi,

I'm trying to build version `1.5` from sources and encounter this error when building the app using `Release scheme`:
`/Users/x/x/x/Battery-Toolkit-main/me.mhaeuser.batterytoolkitd/BTPowerEvents.swift:261:40: Type 'BTPowerEvents' has no member 'getPercentRemaining'`.

After this error I've switched back to `Debug scheme`, the build went smooth, Xcode launched the app, background daemon was created. I've closed the app. And after re-launch it's stuck. Did `uninstall.sh` - the same behavior.\
Built again in Xcode and there are errors in logs:
```
XPC client connected
XPC client remote error, retrying: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process.}
XPC client connected
XPC client remote object error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process.}
Daemon unique ID is nil
Starting daemon service
Updating daemon service
XPC client remote error, retrying: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process.}
XPC client connected
XPC client remote object error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named EMH49F8A2Y.me.mhaeuser.batterytoolkitd was invalidated: failed at lookup with error 3 - No such process.}
Unregistering daemon service
BOOL _NSPersistentUIDeleteItemAtFileURL(NSURL *const __strong) Failed to open directory URL for deletion: file:///Users/x/Library/Saved%20Application%20State/xxx.xxxxxxx.BatteryToolkit.savedState/ restorecount.plist
BOOL _NSPersistentUIDeleteItemAtFileURL(NSURL *const __strong) Failed to open directory URL for deletion: file:///Users/x/Library/Saved%20Application%20State/xxx.xxxxxxx.BatteryToolkit.savedState/ restorecount.plist
```
Bundle names were changed to be able to build the app, so it looks like it's the issue.

**Comment by mhaeuser** [comment]
The Release issue is fixed at: [3d2394ea589bc1c931d6c70b455be5d26d46975b](https://github.com/mhaeuser/Battery-Toolkit/commit/c2dfd19064015984d118c0d85eede3818adc3bdb)

The other issue is a lot more complicated. GUI app and daemon are dependent on the signature certificate configuration for their XPC connection. To properly build and run BT yourself, you need to completely wipe all BT remnants (uninstall.sh unfortunately cannot wipe BTM, see: https://github.com/mhaeuser/Battery-Toolkit/issues/7#issuecomment-2036664963) and use your own certificate setup. This requires changing the related Xcode build variables.

**Comment by mhaeuser** [comment]
It does depend on hardcoded bundle name and certificate CN, yes.

**Comment by mhaeuser** [comment]
Probably once Seqouia enters late beta / GM.
