### ISSUE TITLE
Disabling Power adapter puts computer to sleep in clamshell mode

### ISSUE THREAD

**Issue by slvrscoobie** [mhaeuser/Battery-Toolkit#33]
Ive done this before on previous versions, but on MacOS 15.1 Beta 3 with my M1 at least I tried to turn off the power adapter and my monitors blanked out. Im using a powered docking station with the MBP in clamshell mode. 
I tried to unplug and replug but no luck. If I open the screen it works, but as soon as I close it, the monitors blank out. Turning the power adapter on again, and it works as expected.

**Comment by mhaeuser** [comment]
Is “Prevent for Mac from sleeping when the power adapter is disabled” enabled or disabled?

**Comment by slvrscoobie** [comment]
It is enables.

**Comment by mhaeuser** [comment]
Bizarre. I've just tried on macOS 15 Beta 8 and it works fine. Can you check whether sleep is actually disabled, i.e. is the "Sleep" option in the Apple menu greyed out or enabled?

**Comment by slvrscoobie** [comment]
welp. I guess you can close this, I must have updated it or something as disabling before worked as expected, but it didnt yesterday. Today, after confirming 'prevent Mac from sleeping' was enabled, it's working as expected.
