### ISSUE TITLE
Support for MacOS 15.0 Sequioa

### ISSUE THREAD

**Issue by lloydyu24** [mhaeuser/Battery-Toolkit#37]

**Comment by lloydyu24** [comment]
I am able to install but the interface doesn't load on my end. It tries to
start but doesn't load the GUI.

**Comment by mhaeuser** [comment]
Have you upgraded macOS while Battery Toolkit was installed? Have you tried re-installing it? I know various people using it on Sequoia just fine. I can’t really debug this either or guess what’s wrong.

**Comment by ageorgios** [comment]
![image](https://github.com/user-attachments/assets/cdfb2a26-bf6f-4a9d-aeb1-9209992d35d7)
It says charging on hold, but the battery went from 97% -> 100% mac os sequoia

**Comment by mhaeuser** [comment]
Well, without any information on the scenario (and environment, whether Optimized Charging is on or off, etc.), I cannot say much.

**Comment by yatharth-grover** [comment]
hi dev, if i try to enable charging or disable charging , it requires a complete shut down and restart of the mac. it bugs a lot. says charging to maximum but the settings show that the power source is power adapter and battery's not charging.

**Comment by mhaeuser** [comment]
Is Optimized Charging turned off?

**Comment by MECK187** [comment]
I have updated to Sequioa from a clean Sonoma installation with Battery Toolkit installed pre update. Even though Battery Toolkit and the standard Apple battery indicator would display Charging on Hold/Battery Is Not Charing the battery was charging to the set limit (80%) but would not stop and let it drop to the set limit (70%). 

Re-installing the App fixed the issue for me.

**Comment by mhaeuser** [comment]
Sounds like a macOS bug… sigh. I don’t think I can do much about that, sorry.

**Comment by MECK187** [comment]
No worries. Glad it's working again. Just thought I'm posting it here if someone experiences the same behavior.
