### ISSUE TITLE
XPC client remote error, retrying: Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by nomisx** [mhaeuser/Battery-Toolkit#4]
I have this error.
XPC client remote object error: Couldn’t communicate with a helper application.
Unregistering daemon service
Registering daemon service
Daemon service registering failed, error: Error Domain=SMAppServiceErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedFailureReason=Operation not permitted}, status: 0
Registering daemon service
XPC client connected

How can I fix the error?

Simon

**Comment by mhaeuser** [comment]
Hey, did you reboot after updating? The latest changelog mentions this due to a change of certificate.

**Comment by mhaeuser** [comment]
Assume fixed due to lack of information.
