### ISSUE TITLE
Sync MagSafe indicator light is missing

### ISSUE THREAD

**Issue by IhorLeshko** [mhaeuser/Battery-Toolkit#40]
No toggle for magSafe like on screenshot in readMe.
It is problem on my side? Or it's ok? Thanks

My device: MacBook Air M3

![Screenshot 2024-10-01 at 09 08 07](https://github.com/user-attachments/assets/f36589f5-11b1-474f-92ae-524ebba56ef4)

**Comment by mhaeuser** [comment]
This is still a pre-release feature.
