### ISSUE TITLE
Setting icons are being stretch on external display

### ISSUE THREAD

**Issue by alvin96** [mhaeuser/Battery-Toolkit#42]
I just found a UI glitch on my company's external monitor. The icons in the settings menu are stretched. Nonetheless, thank you for this awesome open-source software!

![image](https://github.com/user-attachments/assets/91a4bbe0-4f5c-4b16-96b6-b55d2671c3af)

This is the display model and the resolution I set:
![image](https://github.com/user-attachments/assets/ac1c81d7-a8d5-48e5-8188-cb418a98b0f3)

**Comment by mhaeuser** [comment]
Do any other applications have this issue? These are native buttons with native icons - super weird.

**Comment by alvin96** [comment]
> Do any other applications have this issue? These are native buttons with native icons - super weird.
Seems like one of my application is also experiencing same issue, likely related to macOS Sequoia. There are no issues on macOS Ventura, so it could be something specific to Sequoia’s display handling. Hopefully, it gets resolved in a future update! Thanks for your fast response. Love this app
![image](https://github.com/user-attachments/assets/f5afe1ea-bc1d-479d-8682-444199001f79)

**Comment by mhaeuser** [comment]
Yes, Crapple trashOS Bugquoia… I moved to 15.1 Beta due to the bugs with System Extensions and network filters, but only the former was resolved (until yesterday)… Sigh.

**Comment by alvin96** [comment]
> Yes, Crapple trashOS Bugquoia… I moved to 15.1 Beta due to the bugs with System Extensions and network filters, but only the former was resolved (until yesterday)… Sigh.

Sigh... I completely agree, recent OS updates seem to prioritize new features over stability, which can be frustrating. Innovation should always build on a solid foundation of stability without sacrificing reliability. It’s hard when progress feels like a tradeoff!
