### ISSUE TITLE
Option to Hide Menu Bar Icon and Access GUI via Applications

### ISSUE THREAD

**Issue by Syiana** [mhaeuser/Battery-Toolkit#43]
Hello,

Thank you for the fantastic application! It would be incredibly useful to have the option to hide the icon in the Menu Bar while still allowing the app to run in the background. For any adjustments, users could simply open the app through Applications (e.g., Applications/Battery-Toolkit), make changes, and close the window when done.

This would streamline the experience for users who prefer a cleaner Menu Bar but still want easy access to settings when needed.

**Comment by mhaeuser** [comment]
This is already possibly, Background Activities (which you enabled during first launch) are always independent of the application that set them up - just quit the GUI.
