### ISSUE TITLE
Battery Toolkit no longer switches to battery when between the charging threshold.

### ISSUE THREAD

**Issue by ghost-bub** [mhaeuser/Battery-Toolkit#59]
Since upgrading to M4 Max, seems like some of the features in the app have stopped working. Aside from the Sync MagSafe light not turning on, it no longer seems to automatically be on battery when it is between the "turn battery charging on below" percentage and the "turn battery charging off above" percentage.

Basically, it will just switch to running off battery adapter instead of draining the battery like it is supposed to do.

Maybe having a feature to choose between power adapter and battery as the power source would be a fix?

For what it is worth, I primarily charge my laptop through a thunderbolt 4 dock TB4 cable instead of magsafe when I'm at my desk. I've seen the same behavior with magsafe, last I checked.

**Comment by mhaeuser** [comment]
The behaviour you describe never occurred. Only “Disable Power Adapter” runs off the battery, otherwise the battery is only a backup in case the AC power is insufficient.
